### ISSUE TITLE
Possibility to install macOS Catalina

### ISSUE THREAD

**Issue by xound78** [corint1/Hackintosh-Lenovo-IdeaPad-530s-14ikb#1]
Hey, did you sucessfully installed macOS Catalina 10.15 with this code? For me it is not working.

**Comment by corint1** [comment]
you are the first to say this ... not only that it installs but runs very well ... I think we do not have the same hardware ...

**Comment by xound78** [comment]
Whats the exact Model Number of your 530S? Mine is 81EU00N9SP

**Comment by corint1** [comment]
81EU00BYRM..the only difference is the screen ... you have 1080p, I have 2k ... I bet you try to change files ... use it as the EFI folder ... without any modification ... all who have it used had no problem ... if you look is rated 5 stars and you are the first to report a problem ...

**Comment by xound78** [comment]
Yes, looks like the screen resolution and SSD are the only differences. Are you still on Catalina Beta 4? Or did you updated to final version of Catalina?

By the way; os 10.14.6 was working good. Only thing that was not working is the trackpad. I solved this with ApplePS2SmartTouchPad.kext. VoodooPS2Controller.kext was not working. Don't ask why.

**Comment by corint1** [comment]
final Catalina...15.1 ... and beta 15.2

for me, the original ssd doesn't even want to format ... I didn't think about it and I changed it ...
i think ssd is the real problem

**Comment by xound78** [comment]
Okay, thanks. I will give it another try! (y)
