### ISSUE TITLE
Trackpadul nu functioneaza

### ISSUE THREAD

**Issue by tvlad1234** [corint1/Hackintosh-Lenovo-IdeaPad-530s-14ikb#2]
Salut! Am instalat macOS Catalina pe un 530s-14ikb (modelul cu BYRM in capat). Totul merge perfect, cu exceptia trackpadului. Am incercat sa folosesc kext-ul ApplePS2SmartTrackPad, tot nu vrea sa mearga. Exista vreo solutie la problema asta?

**Comment by corint1** [comment]
ai folosit configuratia mea ?

**Comment by tvlad1234** [comment]
Da

**Comment by corint1** [comment]
trimite-mi un ioreg...pe semne ca nu sunt aceasi configuratie...al meu este IKB...ca model

**Comment by corint1** [comment]
si un dsdt ....cel original extras cu F4

**Comment by corint1** [comment]
dar inainte incearca sa dai cu un kextutility ...sa repari permisiunile si sa refaci cache-ul ... si un restart bineinteles dupa

**Comment by tvlad1234** [comment]
Am refacut cache-ul, acum functioneaza. Multumesc pentru ajutor!

**Comment by corint1** [comment]
se intampla la instalare noua ...si se va mai intampla la upgrade ... de la o versiune la alta ... daca nu ai nevoie nu update lista de kext...unele merg mai prost ...bafta
